- docs/plan/index.md
> Minor typo fix

- src/feditest/cli/commands/info.py
- src/feditest/cli/commands/list_nodedrivers.py
- src/feditest/cli/commands/list_tests.py
- src/feditest/cli/commands/list_testsets.py
- src/feditest/cli/commands/run.py
- src/feditest/nodedrivers/imp/__init__.py
- src/feditest/protocols/__init__.py
- src/feditest/protocols/activitypub.py
- src/feditest/protocols/fediverse.py
- src/feditest/protocols/web.py
- src/feditest/protocols/webfinger.py
- src/feditest/testplan.py
- src/feditest/testrun.py
- src/feditest/ubos/__init__.py
- src/feditest/utils.py
* Removed semicolons
* Removed unused imports (other than __init__.py files)
* Updated type checks to idiomatic Python
* Removed some unnecessary global declarations
These are based on inspections by the ruff tool. It also seems to have slightly reorganized the imports in a few places.
> Minor code clean up

- pyproject.toml
- src/feditest/__init__.py
- src/feditest/cli/commands/info.py
- src/feditest/cli/commands/list_nodedrivers.py
- src/feditest/cli/commands/list_tests.py
- src/feditest/cli/commands/list_testsets.py
- src/feditest/cli/commands/run.py
- src/feditest/nodedrivers/__init__.py
- src/feditest/nodedrivers/imp/__init__.py
- src/feditest/nodedrivers/mastodon/__init__.py
- src/feditest/nodedrivers/sandbox/__init__.py
- src/feditest/nodedrivers/wordpress/__init__.py
- src/feditest/protocols/__init__.py
- src/feditest/protocols/activitypub.py
- src/feditest/protocols/fediverse.py
- src/feditest/protocols/sandbox.py
- src/feditest/protocols/web.py
- src/feditest/protocols/webfinger.py
- src/feditest/testplan.py
- src/feditest/testrun.py
- src/feditest/ubos/__init__.py
- src/feditest/utils.py
> Some cleanup with the help of pylint

- .gitignore
- src/feditest/testrun.py
- src/feditest/ubos/__init__.py
> Don't attempt to run a UbosNodeDriver on a non-UBOS system

- src/feditest/testrun.py
- tests/test_feditest.py
> Added test summaries. Modified test stub to support new Node API

- src/feditest/testrun.py
> Additional output for default result writer.

- src/feditest/testrun.py
> Add metadata for test runs.

- src/feditest/protocols/webfinger/traffic.py
This fixes an issue where a JSON error message is returned.
> Detect unknown jrd keys

- src/feditest/__init__.py
- src/feditest/nodedrivers/imp/__init__.py
- src/feditest/protocols/web/__init__.py
- src/feditest/templates/metadata.jinja2
- src/feditest/testrun.py
* Conditional redirects
* Conditional content-type checks
* Added feditest user agent since the Python user agent is often rejected.
Test code using this is in a separate repo. Related changes in another PR.
> Various changes to support test code.

- src/feditest/protocols/webfinger/traffic.py
This is based on another PR, therefore extra changes are going to be displayed in the diffs.
> Fix dict compare

- src/feditest/nodedrivers/imp/__init__.py
> Added missing check_content_type arg

- src/feditest/nodedrivers/imp/__init__.py
- src/feditest/nodedrivers/manual/__init__.py
- src/feditest/nodedrivers/saas/__init__.py
- src/feditest/protocols/activitypub/__init__.py
- src/feditest/protocols/web/__init__.py
- src/feditest/protocols/web/traffic.py
- src/feditest/protocols/webfinger/__init__.py
- src/feditest/templates/footer.jinja2
- src/feditest/templates/metadata.jinja2
- src/feditest/templates/report-standalone.jinja2
- src/feditest/templates/session_details.jinja2
- src/feditest/templates/test_matrix.jinja2
- src/feditest/templates/test_summary.jinja2
- src/feditest/testplan.py
- src/feditest/testruncontroller.py
- src/feditest/testruntranscript.py
- src/feditest/ubos/__init__.py
- src/feditest/utils.py
Some changes listed here that are in previous PRs. (not sure how to avoid this?)
* Improve HTML output per https://github.com/fediverse-devnet/feditest/issues/90, https://github.com/fediverse-devnet/feditest/issues/91
* Add failure categories in HTML test output
* Bit of CSS layout messing
* Better labels in HTML
* Add links to feditest.org and add disclaimer to generated HTML
> Css improvements

- src/feditest/testruntranscript.py
> Refactor broken f-string

- src/feditest/protocols/webfinger/traffic.py
This was causing an invalid Lemmy test failure.
> Fixed properties dict kvp iteration

- src/feditest/utils.py
> URIs may have empty paths

- src/feditest/protocols/webfinger/utils.py
See https://github.com/fediverse-devnet/feditest-tests-fediverse/pull/104#issuecomment-2143734253
> Don't crash if query produces null Jrd

- src/feditest/nodedrivers/imp/__init__.py
I was seeing a related error in the test results.
> Handle missing content type

- src/feditest/testruntranscript.py
Was also able to remove the `chdir`.
Fixes #176.
> Fix issue with writing to relative directory.

- src/feditest/cli/commands/convert_transcript.py
> Address mypy complaint

- README-PyPI.md
- README.md
- pyproject.toml
- src/feditest/utils.py
I did the best I could think of based on the docs here: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/
Why it only shows one author: beats me.
> PyPi documentation

- src/feditest/protocols/__init__.py
- src/feditest/testrun.py
Never should have been anything else.
> Make all NodeDrivers singletons

- src/feditest/ubos/__init__.py
> Generalize remote invocation

- tests/test_mastodon_node.py
Skip tests if no mastodon config is present.
> Added fake node driver.

- src/feditest/testrun.py
Transcript won't be written in this case.
Closes #240.
> Checking for empty test result list.

- src/feditest/cli/commands/list-templates.py
> Command to list report templates

- src/feditest/__init__.py
> Fix TypeVar definition.

- src/feditest/nodedrivers/mastodon/__init__.py
- src/feditest/nodedrivers/wordpress/__init__.py
- src/feditest/protocols/activitypub/__init__.py
> PR: fix stupidities

- src/feditest/nodedrivers/mastodon/__init__.py
- src/feditest/registry.py
- src/feditest/templates/default/partials/shared/summary.jinja2
- src/feditest/testrun.py
Make sandbox work again and a few other small errors
> Pr fix sandbox errors

- src/feditest/cli/commands/run.py
> Alias for --json: --testresult

- src/feditest/testplan.py
- src/feditest/testruntranscript.py
- tests/test_report_node_driver_errors.py
> Create pytest that tests we report on NodeDriver errors.

- .pre-commit-config.yaml
- src/feditest/nodedrivers/mastodon/__init__.py
- src/feditest/registry.py
> Add mypy to pre-commit. Fix a few small issues.

- .pre-commit-config.yaml
- tests/test_mastodon_node.py
- tests/test_registry.py
Also includes a few auto-fixes by ruff.
> Enabled pre-commit hook for ruff linting

- src/feditest/nodedrivers/imp/__init__.py
- src/feditest/nodedrivers/manual/__init__.py
- src/feditest/nodedrivers/mastodon/__init__.py
- src/feditest/nodedrivers/mastodon/ubos.py
- src/feditest/nodedrivers/saas/__init__.py
- src/feditest/nodedrivers/sandbox/__init__.py
- src/feditest/nodedrivers/wordpress/__init__.py
- src/feditest/nodedrivers/wordpress/ubos.py
- src/feditest/protocols/__init__.py
- src/feditest/protocols/web/__init__.py
- src/feditest/testrun.py
- src/feditest/ubos/__init__.py
This is preparatory work for adding pre-defined users.
> Pass Node definition from TestPlan into Node provisioning

- tests/test_report_node_driver_errors.py
> Fix failing unit test.

- src/feditest/utils.py
> Ignore exceptions that occur in the browsed code when we discover tests or nodedrivers

- src/feditest/__init__.py
- src/feditest/cli/commands/run.py
- src/feditest/nodedrivers/mastodon/ubos.py
- src/feditest/registry.py
- src/feditest/testrun.py
- src/feditest/ubos/__init__.py
> Fix run --domain

- src/feditest/nodedrivers/fallback/fediverse.py
- src/feditest/nodedrivers/mastodon/__init__.py
- src/feditest/protocols/fediverse/__init__.py
Also clarify some comments, better console messages.
> Fixes for https://github.com/fediverse-devnet/feditest-tests-fediverse/issues/141

- src/feditest/cli/util.py
> Use the correct test name.

- src/feditest/cli/commands/create_session_template.py
- src/feditest/cli/commands/create_testplan.py
- src/feditest/cli/commands/run.py
> Use action=append instead of nargs=+ for --test argument.

- src/feditest/nodedrivers/__init__.py
- src/feditest/nodedrivers/fallback/fediverse.py
- src/feditest/nodedrivers/manual/__init__.py
> Improve interactive prompts.

- LICENSE
- REUSE.toml
> Add REUSE.toml
