fediverse-devnet/feditest

src/feditest/cli/commands/run.py
src/feditest/testrun.py
tests/test_feditest.py

* Added a TestResultWriter typing.Protocol
* Encapsulated current reporting behavior in a default writer
* Added a TAP-based result writer
* Extended the test problem reporting
* Exposed a few fields on `TestRunSession` (`name` and `problems`)
* Added a `run` argument to enable TAP output to stdout or a file.
* Added basic unit tests for writers.
When there is framework plugin support, this can be modified to use it.
Closes #39.

Initial TAP result writing support.

---

src/feditest/testrun.py
tests/test_feditest.py

The issue was that I was formatting the TestProblem instead of the exception. I manually tested that str(problem.exc) for a hamcrest AssertionError is the same output as `hamcrest.core.string_description.tostring`. I also added a unit test for a hamcrest exception (versus some other kind of thrown from the test).
Closes #59.

Use formatted exception instead of TestProblem for TAP

---

pyproject.toml
src/feditest/cli/commands/run.py
src/feditest/templates/report.jinja2
src/feditest/templates/session_details.jinja2
src/feditest/templates/test_matrix.jinja2
src/feditest/templates/test_summary.jinja2
src/feditest/testrun.py

This is an initial prototype of an HTML test report. It includes a summary section, a test matrix, and a session details section. These are coded so they can be easily used individually if, for example, you just want the test matrix.
You can see an example report at https://stevebate.net/feditest/report.html. I did minimal styling with this and it's not mobile ready (AFAIK). The report is primarily intended to provide a basis for further discussion.
The report is generated from a test plan that I created to test WebFinger against Mastodon, Pleroma, Akkoma and Threads.
There are obvious challenges we need to address. The  automatically-generated session names are not very report-friendly. There are client/server roles (vs leader/follower), but there are no nice report-friendly names for …

HTML results / report generator

---

src/feditest/__init__.py
src/feditest/reporting.py
src/feditest/testrun.py
src/feditest/testruncontroller.py
src/feditest/testruntranscript.py

In Python, "user" exceptions derive from the `Exception` class. The `BaseException` type is not intended to be directly caught (except maybe in very special circumstances) since it includes exceptions like `SystemExit` and `KeyboardInterrupt` (the reason for this PR).
The `BaseException` type is also not intended for subclassing program (aka, "user") exceptions. The `Exception` class or a subclass should be used for that.
Catching `BaseException` means that the test run cannot be interrupted from the keyboard (ctrl-c on most operating systems) after it is started. That's undesirable for a large test run where some unexpected exceptions are seen in the console output and a developer (like me) wants to stop the run at that point.

Use Exception instead of BaseException.

---

src/feditest/utils.py

Closes #106.
This is causing some incorrect failures.
I only added uppercase letters to the regex. You probably know this, but the regex will allow invalid URIs for other reasons (e.g., `acct:foo@-:-`), but a completely correct regex for the hostname part of a URI is very complex.

Allow uppercase letters in account URIs

---

src/feditest/nodedrivers/imp/__init__.py
src/feditest/nodedrivers/manual/__init__.py
src/feditest/nodedrivers/saas/__init__.py
src/feditest/protocols/activitypub/__init__.py
src/feditest/protocols/web/__init__.py
src/feditest/protocols/web/traffic.py
src/feditest/protocols/webfinger/__init__.py
src/feditest/testplan.py
src/feditest/ubos/__init__.py
src/feditest/utils.py

* Sometimes we want to validate and parse an identifier, and sometimes we only want to validate. Have separate calls for that.
* Make ParsedUri more useful by also using it for acct: URIs; new subclasses; move to utils
* Better invalid-URI checking

Unconfuse parse_validate API

---

src/feditest/nodedrivers/imp/__init__.py

I did some investigation into why the tests weren't seeing CORS headers from Mastodon given they have configured CORS middleware for the `.well-known/*` route. It turns out that the CORS headers are not sent unless there's an Origin header (which a browser would send). I made a very simple change to add the header. The domain doesn't matter in this case.
Although very strict enforcement of the RFC would require the CORS header even without the "Origin" header, it seems that the existing behavior satisfies the spirit of the RFC requirement -- that browsers can make queries to the WebFinger endpoint.
I don't know what other servers have the same behavior.

Added Origin header for conditional CORS headers

---

src/feditest/protocols/__init__.py
src/feditest/testruntranscript.py

Count tests that cannot be run because a Node or NodeDriver doesn't implement a method as skipped.

---

src/feditest/nodedrivers/imp/__init__.py
src/feditest/protocols/web/__init__.py
src/feditest/protocols/webfinger/__init__.py
src/feditest/protocols/webfinger/traffic.py
src/feditest/protocols/webfinger/utils.py

* Changing the WebFingerClient API slightly: Instead of throwing an Exception the first time the an implementing class doesn't like something, don't throw but return a set of all problems. This is probably what a good library would do, so that the code invoking the library could report errors nicely. It allows us to filter out certain errors when running certain tests, so that the errors reported in a given test actually match what the test is trying to test.
* Better and more consistent error reporting
* Fix incorrect ClaimedJrd recursive comparison
* Fix the Imp API to match the WebFingerClient API (has consequences for the actual tests)

Fix imp api

---

src/feditest/cli/commands/convert_transcript.py
src/feditest/templates/multifile/partials/test_matrix/table.jinja2
src/feditest/templates/multifile/partials/test_session/metadata.jinja2
src/feditest/templates/multifile/partials/test_session/results.jinja2
src/feditest/templates/multifile/partials/test_session/title.jinja2
src/feditest/templates/multifile/static/css/common.css
src/feditest/templates/multifile/static/css/feditest.css
src/feditest/templates/multifile/test_matrix.jinja2
src/feditest/templates/multifile/test_session.jinja2
src/feditest/testplan.py
src/feditest/testruntranscript.py

(Documented in the code...)
Generates the Feditest reports into a test matrix and a linked, separate
file per session. It uses a template path so variants of reports can be generated
while sharing common templates. The file_ext can be specified to support generating
other formats like MarkDown.
The generation uses two primary templates. The `test_matrix.jinja2` template is used for
the matrix generation and 'test_session.jinja2' is used for session file generation.
Any files in a directory called "static" in a template folder will be copied verbatim
to the output directory (useful for CSS, etc.). If a file exists in the static folder of more
than one directory in the template path, earlier path entries will overwrite later ones.
The current templates are placeholders. I think it's close …

Added multifile report generation and placeholder templates.

---

src/feditest/cli/commands/convert_transcript.py
src/feditest/testruntranscript.py

Changed default template path to 'multifile,.'
so the placeholder templates can use the non-
multifile partial templates. After the placeholder templates are 
replaced with the real ones, we should modify this
default path, if needed.
Fixes #179.

Change/fix the default multifile template path for the placeholder templates.

---

src/feditest/utils.py

Data URIs do not have a network location.  Nevertheless they are fully valid URIs.
Fixes #197

Allow "data" URIs in webfinger results. (#197)

---

src/feditest/nodedrivers/mastodon/manual.py
src/feditest/nodedrivers/mastodon/mixin.py
src/feditest/nodedrivers/mastodon/ubos.py
tests/test_mastodon_node.py

I factored out the Mastodon API-related code into a "mixin" class. I used the mixin to create a manually-provisioned Mastodon node and I also added it to the UBOS-based node. For now, the account parameters for UBOS should be configured explicitly. If you implement dynamic actor creation that can be supported too. See the example test plan in the feditest-tests-fediverse repo for more details about configuration.

Mastodon API node mixin

---

src/feditest/templates/default/partials/test_matrix/table.jinja2
src/feditest/templates/default/partials/test_matrix/testresult.jinja2
src/feditest/templates/default/partials/test_session/results.jinja2
src/feditest/templates/default/static/feditest.css

CSS :target highlight if a specific test result is identified in a URL fragment Also: fixed text color in hover popup in dark mode

CSS for fragments identifying tests per #202

---

Makefile

I tried to run `make venv` in an environment with only `python3`, no installed `python`.  It told me to try running with the `PYTHON` environment variable.  However, this didn't actually work.  This variable should be overridable from the command line.

Allow overriding PYTHON executable path

---

src/feditest/protocols/__init__.py
src/feditest/protocols/webfinger/__init__.py

This fixes #200 by remembering values for valid and invalid accounts entered by the user.

Memoise previous responses to prompt for account URIs

---

src/feditest/cli/commands/convert_transcript.py
src/feditest/testruntranscript.py

Added diagnostics for missing HTML templates.
Closes #217.

Updated --template name and help.

---

src/feditest/nodedrivers/imp/__init__.py
src/feditest/nodedrivers/saas/__init__.py
src/feditest/protocols/web/__init__.py
src/feditest/protocols/webfinger/__init__.py

Closes #183
When defining a node, use the `server-prefix` parameter instead of hostname. The server prefix is in the form `<scheme>://<hostname>[:<port>]` (no trailing slash). This *should* be backward-compatible. The `hostname` parameter should still work too, but note that the existing code ignores that parameter when constructing WebFinger queries. The resource URI hostname is used instead.

Feditest side of http support changes

---

src/feditest/__init__.py

1. Add return type annotation (helps with IDE)
2. Return the annotated type (so import works)

Update nodedriver decorator

---

tests/test_registry.py

Was seeing:
```
FAILED tests/test_registry.py::test_save_restore - TypeError: NamedTemporaryFile() 
got an unexpected keyword argument 'delete_on_close'
```

Fixed error with unsupported delete_on_close keyword arg

---

tests/test_report_node_driver_errors.py

The `TestException` was confusing pytest test discovery (at least in a VS Code context) because of the "Test*" naming convention for test classes.

Renamed TestException

---

RELEASE-HOWTO.md
pyproject.toml

so we don't get unexpected surprises when somebody runs it on debian or such. Fixes #307.
There does not seem to be a way to specify different version requirements for development vs production, so added lots of comments to do this manually.

Fix development of feditest to python version 3.11

---

src/feditest/utils.py

The version check was originally this way so that the `feditest` package didn't need to be installed for development purposes (to get the package version).

Default version without installed package.

---

src/feditest/nodedrivers/mastodon/__init__.py

(Caught by ruff...)
The `mastodon_user_client` field was being overwritten by the `mastodon_user_client` function. I changed the name of the field and made it hidden since it's a private cache of the API instance.

Fixed clashing field and function name

---

.pre-commit-config.yaml
pyproject.toml

See also: #259
Most of the checks are currently commented out because it's going to "clean up" a lot of files (and will flag many more as needing manual intervention). I thought I'd enable them one at a time and submit a PR with the changes. I also need to see how to use the pytest support given our somewhat ad hoc venv approach (the checks run in their own isolated virtual environment).
To use this:
```
pip install pre-commit  # or however you are installing feditest dependencies
pre-commit install 
pre-commit run -a
pre-commit run -a <check-id>
git push --no-verify

Initial pre-commit support.

---

pyproject.toml
src/feditest/nodedrivers/mastodon/__init__.py
src/feditest/protocols/webfinger/__init__.py
src/feditest/registry.py

This is overall improving things with the Mastodon Node, although more work remains.
* Make the random domain a bit longer
* Better name for our custom CA
* Add x509 SubjectAlternativeName to cert: apparently python ssl needs it
* Added types-requests dependency to make mypy happy
* Mastodon.py can now create the OAuth app using our custom CA

Make the custom CA work with Mastodon.py

---

.pre-commit-config.yaml
tests/test_mastodon_node.py

Disabled test_mastodon_node temporarily until it is passing again. 
Also updated mypy to autoinstall type libraries.

Added pytest hook.

---

pyproject.toml

This solves my mystery ruff problem where ruff would complain about ExceptionGroup not existing, although I'm running python 3.11. Why I need it and others don't IDK.

Solve mystery ruff problem

---

src/feditest/nodedrivers/mastodon/__init__.py
src/feditest/nodedrivers/mastodon/ubos.py
src/feditest/protocols/__init__.py
src/feditest/ubos/__init__.py
tests/feditest/mastodon_mastodon.py

so Mastodon will not block HTTP requests on the local network, which we need for testing purposes.
Closes #343

Use new UBOS `allow_private_addresses` customizationpoint on Mastodon and make test work

---

src/feditest/nodedrivers/mastodon/__init__.py
src/feditest/protocols/fediverse/__init__.py
src/feditest/testrun.py

(this PR is smaller than it looks like -- my local branches got a bit messy)

Support testing direct messages (via @mention) in Mastodon

---

.pre-commit-config.yaml
Makefile
src/feditest/nodedrivers/mastodon/__init__.py

Make mypy invocation from inside pre-commit and standalone more consistent. Partial success only.

mypy setup improvements

---

src/feditest/nodedrivers/mastodon/__init__.py
src/feditest/nodedrivers/wordpress/__init__.py
src/feditest/nodedrivers/wordpress/ubos.py
src/feditest/ubos/__init__.py

WordPress needs to have its own Account implementation -- different path than Mastodon
Added OAuth token account provisioning code from Enable_Mastodon_Apps developer
Throw Exception if mastodon_user_client was about to return None

Make progress on WordPress+ActivityPubPlugin. Not working yet.

---

src/feditest/protocols/__init__.py
src/feditest/registry.py

Allow registry to generate certs for hostnames specified in the TestPlan

---

src/feditest/cli/commands/run.py

Now that we have more complex ways that we can invoke "feditest run", having a default test plan makes less sense, and error messages are becoming hard to understand given how many options there are.

Remove the default testplan argument value from run.

---

src/feditest/__init__.py
src/feditest/cli/commands/run.py
src/feditest/nodedrivers/wordpress/__init__.py
src/feditest/nodedrivers/wordpress/ubos.py
tests.smoke/wordpress.saas.constellation.json
tests.smoke/wordpress.ubos.constellation.json
tests.smoke/wordpress_mastodon.ubos.constellation.json

Rename WordPress Driver 

---

src/feditest/cli/commands/convert_transcript.py
src/feditest/cli/commands/create_constellation.py
src/feditest/cli/commands/create_session_template.py
src/feditest/cli/commands/create_testplan.py
src/feditest/cli/commands/info.py
src/feditest/cli/commands/list-templates.py
src/feditest/cli/commands/list_nodedrivers.py
src/feditest/cli/commands/list_tests.py
src/feditest/cli/commands/run.py
src/feditest/cli/commands/version.py
src/feditest/cli/utils.py

Fixes #379 
Also, lint improvements

Better --node error message

---

src/feditest/cli/utils.py
src/feditest/nodedrivers/ubos.py
src/feditest/testplan.py
src/feditest/testruntranscriptserializer/html.py
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/matrix.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/matrix/matrix.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/matrix/metadata.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/matrix/testresult.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/shared/summary.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/shared_session/metadata.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/shared_session/results.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/partials/shared_session/testresult.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/session_single.jinja2
src/feditest/testruntranscriptserializer/templates/testplantranscript_default/session_with_matrix.jinja2
src/feditest/utils.py
tests.unit/test_30_create_testplan.py
tests.unit/test_40_fallback_fediverse_accounts_from_testplan.py
tests.unit/test_40_report_node_driver_errors.py
tests.unit/test_40_ubos_mastodon_accounts_from_testplan.py
tests.unit/test_50_run_assertion_raises.py
tests.unit/test_50_run_exceptions.py
tests.unit/test_50_run_multistep_assertion_raises.py
tests.unit/test_50_run_not_implemented.py
tests.unit/test_50_run_passes.py
tests.unit/test_50_run_skip.py
tests.unit/test_50_run_testplan_sandbox.py

Sanitize input and HTML output better
